version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=evgenii
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_FLYWAY_USER=evgenii
      - SPRING_FLYWAY_PASSWORD=test
    depends_on:
      - db

  react-app:
    build:
      context: ../CTR-EvPM-Visualisation-Frontend  # Replace with the path to your React app
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Expose port 3000 on the host and map to port 80 in the container
    depends_on:
      - app

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=evgenii
      - POSTGRES_PASSWORD=test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
