server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: evgenii
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: evgenii
    locations: classpath:db/migration
    enabled: true